"""first init db

Revision ID: 4297f8e82897
Revises: 1d17d57a1093
Create Date: 2017-11-16 16:17:10.459651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4297f8e82897'
down_revision = '1d17d57a1093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'comments', ['email'])
    op.create_unique_constraint(None, 'comments', ['user_id'])
    op.drop_constraint(u'comments_ibfk_2', 'comments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'comments_ibfk_2', 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
