"""first init db

Revision ID: 43d9d315d19b
Revises: 4297f8e82897
Create Date: 2017-11-16 16:23:04.251863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43d9d315d19b'
down_revision = '4297f8e82897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('email', table_name='comments')
    op.drop_index('user_id', table_name='comments')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('user_id', 'comments', ['user_id'], unique=True)
    op.create_index('email', 'comments', ['email'], unique=True)
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
