"""first init db

Revision ID: d1ee1d9d3685
Revises: d86341d97b56
Create Date: 2017-11-27 23:38:31.712694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1ee1d9d3685'
down_revision = 'd86341d97b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c5game', 'max')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c5game', sa.Column('max', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
