"""first init db

Revision ID: e29643b24447
Revises: bb1c31191c59
Create Date: 2017-08-10 18:24:36.964721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29643b24447'
down_revision = 'bb1c31191c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('verify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'verify')
    # ### end Alembic commands ###
