"""first init db

Revision ID: ea85bc491295
Revises: d1ee1d9d3685
Create Date: 2017-11-28 13:07:37.429476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea85bc491295'
down_revision = 'd1ee1d9d3685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c5game', sa.Column('verify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c5game', 'verify')
    # ### end Alembic commands ###
